Portfolio/Portfolio/Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

Portfolio/Portfolio/portfolio/urls.py
from pipes import Template
from django.urls import path as url
from .views import CreatePhone, TemplateViewSet, WatchesViewSet, AboutViewSet,  \
ContactViewSet, UserCreateView, LoginingView, Logout, CreateProduct, \
PhoneViewSet, CategoryViewSet, LaptopViewSet, IpodViewSet, HeadphonesViewSet, PCViewSet, \
CreatePhone

urlpatterns = [
    url('', TemplateViewSet.as_view(), name="templateviewset"),
    url('timups/category/watches', WatchesViewSet.as_view(), name="watchesviewset"),
    url('timups/category/phone', PhoneViewSet.as_view(), name="phoneviewset"),
    url('timups/category/laptop', LaptopViewSet.as_view(), name="laptopviewset"),
    url('timups/category/ipod', IpodViewSet.as_view(), name="ipodviewset"),
    url('timups/category/pc', PCViewSet.as_view(), name="PCviewset"),
    url('timups/category/headphones', HeadphonesViewSet.as_view(), name="headphonsviewset"),
    url('timups/about', AboutViewSet.as_view(), name="aboutviewset"),
    url('timups/category', CategoryViewSet.as_view(), name="categoryviewset"),
    url('timups/contact', ContactViewSet.as_view(), name="contactviewset"),
    url('register/', UserCreateView.as_view(), name='register'),
    url('login/', LoginingView.as_view(), name='login'),
    url('logout/', Logout.as_view(), name='logout'),
    url('timups/create/watch', CreateProduct.as_view(), name='watches'),
    url('timups/create/phone', CreatePhone.as_view(), name='phones'),
]

Portfolio/Portfolio/portfolio/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.forms import BooleanField, CharField, FloatField, SlugField
import jwt
from datetime import datetime
from datetime import timedelta
from django.conf import settings
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

USER_MODEL = settings.AUTH_USER_MODEL

class UserManager(BaseUserManager):
    def _create_user(self, username, email, password=None, **extra_fields):
        if not username:
            raise ValueError('Указанное имя пользователя должно быть установлено')

        if not email:
            raise ValueError('Данный адрес электронной почты должен быть установлен')

        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Суперпользователь должен иметь is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Суперпользователь должен иметь is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(db_index=True, max_length=255, unique=True)
    email = models.EmailField(validators=[validators.validate_email], unique=True, blank=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('username',)
    objects = UserManager()

    def __str__(self):
        return f'{self.username} {self.email}'
    @property
    def token(self):
        return self._generate_jwt_token()

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    def generate_jwt_token(self):
        dt = datetime.now() + timedelta(days=60)

        # token = jwt.encode({'id': self.pk, 'exp': int(dt.strftime('%s')) }, settings.SECRET_KEY, algorithm='HS256')
        token = jwt.encode({
             'id': self.pk,
             'exp': dt.utcfromtimestamp(dt.timestamp())    #CHANGE HERE
    }, settings.SECRET_KEY, algorithm='HS256')
        return token

class Watch(models.Model):
    name_model = models.CharField(max_length=50)
    model_price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='media/', blank=True, null=True)
    color = models.CharField(max_length=20)
    cm = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.name_model} {self.model_price} {self.cm}'


    
class Phone(models.Model):
    name_model = models.CharField(max_length=100)
    model_price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='media/', blank=True, null=True)
    color = models.CharField(max_length=20)
    diagonal = models.PositiveIntegerField()
    wifi = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name_model} {self.model_price} {self.color}'

Portfolio/Portfolio/portfolio/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import CustomUser, Watch, Phone

class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    repeat_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password', 'repeat_password')

    def clean(self):
        data = self.cleaned_data
        if data.get('password') != data.get('repeat_password'):
            raise forms.ValidationError('Passwords do not match!')
        return data

class WatchForm(forms.ModelForm):
    class Meta:
        model = Watch
        fields = '__all__'

class PhoneForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = '__all__'

Portfolio/Portfolio/portfolio/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from .models import CustomUser, Watch, Phone
from .forms import CustomUserForm, WatchForm, PhoneForm

#TemplateViewSets
class TemplateViewSet(ListView):
    template_name = 'base.html'
    model = Watch
    queryset = Watch.objects.all()


class WatchesViewSet(ListView):
    template_name = 'watches.html'
    model = Watch
    queryset = Watch.objects.all()

class AboutViewSet(ListView):
    template_name = 'about.html'

    def get_queryset(self):
        ...

class ContactViewSet(ListView):
    template_name = 'contact.html'

    def get_queryset(self):
        ...

class PhoneViewSet(ListView):
    template_name = 'phone.html'
    model = Phone
    queryset = Phone.objects.all()

class CategoryViewSet(ListView):
    template_name = 'category.html'

    def get_queryset(self):
        ...

class LaptopViewSet(ListView):
    template_name = 'laptop.html'

    def get_queryset(self):
        ...

class IpodViewSet(ListView):
    template_name = 'ipod.html'

    def get_queryset(self):
        ...

class PCViewSet(ListView):
    template_name = 'PC.html'

    def get_queryset(self):
        ...

class HeadphonesViewSet(ListView):
    template_name = 'headphones.html'

    def get_queryset(self):
        ...
##############################

#Login and Register and Logout

class LoginingView(LoginView):
    success_url = reverse_lazy('templateviewset')
    template_name = 'login.html'

    def get_success_url(self):
        return self.success_url

    def form_valid(self, form):
        return super().form_valid(form=form)

class UserCreateView(CreateView):
    model = CustomUser
    form_class = CustomUserForm
    success_url = '/login/'
    template_name = 'register_page.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.set_password(self.object.password)
        self.object.save()
        return super().form_valid(form)


class Logout(LogoutView):
    next_page = '/'

################################

#CreatedProduct

class CreateProduct(CreateView):
    model = Watch
    form_class = WatchForm
    success_url = reverse_lazy('templateviewset')
    template_name = 'create_product.html'

class CreatePhone(CreateView):
    model = Phone
    form_class = PhoneForm
    success_url = reverse_lazy('templateviewset')
    template_name = 'create_phone.html'

###############################

    

Portfolio/Portfolio/portfolio/templates/PC.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_superuser %}
<a href="{% url 'watches' %}" class="btn btn-info">Создать товар</a>
{% endif %}
<section class="shop_section layout_padding">
  <div class="container">
    <div class="heading_container heading_center">
      <h2>
        Latest PC
      </h2>
    </div>
    <div class="row" style="display:inline-block">
      <div class="col-sm-6 col-xl-3">
        <div class="box"style="display:inline-block; width: 250px; height: 300px" >
          <!-- <a href=""> -->
            <div class="img-box" >
              <img src="{% static 'images/PC.png'%}" alt="">
            </div>
            <div class="detail-box">
              <h6>
                {{ watch.name_model }}
              </h6>
              <h6>
                Price:
                <span>
                  ${{ watch.model_price }}
                </span>
              </h6>
            </div>
            <div class="new">
              <a href="#">
                Купить
              </a>
            </div>
          <!-- </a> -->
        </div>
      </div>
    </div>
<!--paginations-->     <!-- <div class="btn-box">
      <a href="">
        View All
      </a>
    </div> -->
  </div>
</section>

  <!-- end shop section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_detail">
            <h4>
              About
            </h4>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Reach at..
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Subscribe
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </div>
  </footer>
</body>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <section class="about_section layout_padding">
    <div class="container  ">
      <div class="row">
        <div class="col-md-6 col-lg-5 ">
          <div class="img-box">
            <img src="{% static 'images/about-img.png'%}" alt="">
          </div>
        </div>
        <div class="col-md-6 col-lg-7">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
              in some form, by injected humour, or randomised words which don't look even slightly believable. If you
              are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
              the middle of text. All
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_detail">
            <h4>
              About
            </h4>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Reach at..
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Subscribe
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </div>
  </footer>
</body>
{% endblock %}

</html>

Portfolio/Portfolio/portfolio/templates/category.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="shop_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2 style="padding-right: 80px;">
          Category
        </h2>
      </div>
<div class="row" style="display:inline-block">
    <div class="col-sm-6 col-xl-3">
      <div class="box"style="display:inline-block; width: 250px; height: 300px" >
        <!-- <a href=""> -->
          <div class="img-box" >
            <img src="{% static 'images/w1.png'%}" alt="">
          </div>
          <div class="detail-box">
            <h6>

            </h6>
            <h6>
              
              <span>
                
              </span>
            </h6>
          </div>
          <div class="new" style="width: 250px;">
            <a href="{% url 'watchesviewset' %}" style="width: 250px; text-align: center;">
                Watch
            </a>
          </div>
        <!-- </a> -->
      </div>
    </div>
  </div>
<div class="row" style="display:inline-block; padding-left: 150px">
    <div class="col-sm-6 col-xl-3">
      <div class="box"style="display:inline-block; width: 250px; height: 300px;" >
        <!-- <a href=""> -->
          <div class="img-box" >
            <img src="{% static 'images/phone01.png'%}" alt="">
          </div>
          <div class="detail-box">
            <h6>

            </h6>
            <h6>
              
              <span>
                
              </span>
            </h6>
          </div>
          <div class="new" style="width: 250px;">
            <a href="{% url 'phoneviewset' %}" style="width: 250px; text-align: center;">
                Phone
            </a>
          </div>
        <!-- </a> -->
      </div>
    </div>
  </div>
  <div class="row" style="display:inline-block; padding-left: 150px">
    <div class="col-sm-6 col-xl-3">
      <div class="box"style="display:inline-block; width: 250px; height: 300px;" >
        <!-- <a href=""> -->
          <div class="img-box" >
            <img src="{% static 'images/laptop.png'%}" alt="">
          </div>
          <div class="detail-box">
            <h6>

            </h6>
            <h6>
              
              <span>
                
              </span>
            </h6>
          </div>
          <div class="new" style="width: 250px;">
            <a href="{% url 'laptopviewset' %}" style="width: 250px; text-align: center;">
                Laptop
            </a>
          </div>
        <!-- </a> -->
      </div>
    </div>
  </div>
  <div class="row" style="display:inline-block">
    <div class="col-sm-6 col-xl-3">
      <div class="box"style="display:inline-block; width: 250px; height: 300px" >
        <!-- <a href=""> -->
          <div class="img-box" >
            <img src="{% static 'images/ipod.png'%}" alt="">
          </div>
          <div class="detail-box">
            <h6>

            </h6>
            <h6>
              
              <span>
                
              </span>
            </h6>
          </div>
          <div class="new" style="width: 250px;">
            <a href="{% url 'ipodviewset' %}" style="width: 250px; text-align: center;">
                Ipod
            </a>
          </div>
        <!-- </a> -->
      </div>
    </div>
  </div>
  <div class="row" style="display:inline-block; padding-left: 150px">
    <div class="col-sm-6 col-xl-3">
      <div class="box"style="display:inline-block; width: 250px; height: 300px;" >
        <!-- <a href=""> -->
          <div class="img-box" >
            <img src="{% static 'images/PC.png'%}" alt="">
          </div>
          <div class="detail-box">
            <h6>

            </h6>
            <h6>
              
              <span>
                
              </span>
            </h6>
          </div>
          <div class="new" style="width: 250px;">
            <a href="{% url 'PCviewset' %}" style="width: 250px; text-align: center;">
                PC
            </a>
          </div>
        <!-- </a> -->
      </div>
    </div>
  </div>
  <div class="row" style="display:inline-block; padding-left: 150px">
    <div class="col-sm-6 col-xl-3">
      <div class="box"style="display:inline-block; width: 250px; height: 300px;" >
        <!-- <a href=""> -->
          <div class="img-box" >
            <img src="{% static 'images/Pods.png'%}" alt="">
          </div>
          <div class="detail-box">
            <h6>

            </h6>
            <h6>
              
              <span>
                
              </span>
            </h6>
          </div>
          <div class="new" style="width: 250px;">
            <a href="{% url 'headphonsviewset' %}" style="width: 250px; text-align: center;">
                Headphones
            </a>
          </div>
        <!-- </a> -->
      </div>
    </div>
  </div>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
  <section class="contact_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <div class="heading_container">
              <h2>
                Contact Us
              </h2>
            </div>
            <form action="">
              <div>
                <input type="text" placeholder="Full Name " />
              </div>
              <div>
                <input type="email" placeholder="Email" />
              </div>
              <div>
                <input type="text" placeholder="Phone number" />
              </div>
              <div>
                <input type="text" class="message-box" placeholder="Message" />
              </div>
              <div class="d-flex ">
                <button>
                  SEND
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="img-box">
            <img src="{% static 'images/contact-img.jpg'%}" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end contact section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_detail">
            <h4>
              About
            </h4>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Reach at..
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Subscribe
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </div>
  </footer>
</body>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/create_phone.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<form class="container" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Create</button>
</form>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/create_product.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<form class="container" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Create</button>
</form>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <form class="container-sm" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success">Login</button>
        <a class="btn btn-danger" href="{% url 'register' %}" >Create account</a>
    </form>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/register_page.html
{% extends 'base.html' %}

{% block title %} Registration {% endblock %}

{% block content %}
    <form class="container" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Register</button>
    </form>
{% endblock %}

Portfolio/Portfolio/portfolio/templates/watches.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_superuser %}
<a href="{% url 'watches' %}" class="btn btn-info">Создать товар</a>
{% endif %}
<section class="shop_section layout_padding">
  <div class="container">
    <div class="heading_container heading_center">
      <h2>
        Latest Watches
      </h2>
    </div>
  {% for watch in watch_list %}
    <div class="row" style="display:inline-block">
      <div class="col-sm-6 col-xl-3">
        <div class="box"style="display:inline-block; width: 250px; height: 300px" >
          <!-- <a href=""> -->
            <div class="img-box" >
              <img src="{% static 'images/w1.png'%}" alt="">
            </div>
            <div class="detail-box">
              <h6>
                {{ watch.name_model }}
              </h6>
              <h6>
                Price:
                <span>
                  ${{ watch.model_price }}
                </span>
              </h6>
            </div>
            <div class="new">
              <a href="#">
                Купить
              </a>
            </div>
          <!-- </a> -->
        </div>
      </div>
    </div>
  
    {% endfor %}
<!--paginations-->     <!-- <div class="btn-box">
      <a href="">
        View All
      </a>
    </div> -->
  </div>
</section>

  <!-- end shop section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_detail">
            <h4>
              About
            </h4>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Reach at..
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Subscribe
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </div>
  </footer>
</body>
{% endblock %}